---
- name: Install prerequisites.
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - curl

- name: Add the GPG key.
  apt_key:
    id: 0A1C1655A0AB68576280
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add the repositories.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb https://deb.nodesource.com/node_8.x {{ ansible_lsb.codename }} main
    - deb-src https://deb.nodesource.com/node_8.x {{ ansible_lsb.codename }} main

- name: Install Node.js.
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Update npm.
  npm:
    global: yes
    name: npm
    state: latest
